### PR TITLE
Fix: Update minor UI elements

### LINKED ISSUE #297: Matching Cookie Table top Bar background color matching with DevTools in Light Mode
**Describe the bug**
The top Bar from the Cookie Data Table panel on light mode has a different background color than DevTools, the color should match the Applications tab top Bar:

Application Tab:
Screenshot 2023-11-22 at 13 57 16

Cookie Data Table:
Screenshot 2023-11-22 at 13 57 04

As we can see in the screenshot above, the Extension top Bar has a gray color, the DevTools top Bar has a white color.

**To Reproduce**
1. Set the OS to light mode
2. Open the Extension
3. Go to the cookies data panel selection the analyzed URL 
4. Compare the top bar color with the Applications tab 

**Expected behavior**
The top bar at the cookies data table should have a white background, such as the application tb top bar

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser 119.0.6045.159 (Official Build) (arm64) 
 - Version: develop

### PR DESCRIPTION
**Pull request by mayan-000**
## Description
This PR aims to implement a few UI changes requested
- Update the frame's horizontal matrix description.
- Make the table top-bar bg color consistent with the Application tab.
- Put Unknown platform if not available in devtools.

## Screenshot/Screencast
Screenshot 2023-12-27 at 5 05 20 PM
Screenshot 2023-12-27 at 5 05 41 PM

---

Fixes #297 #298 #319

### CODE REVIEW

File: packages/design-system/src/components/cookiesLanding/cookiesMatrix/index.tsx [hunk 1]
```diff
@@ -91,13 +91,13 @@ const CookiesMatrix = ({
...
           title: 'Number of Frames',
-          description: 'Number of frames found on the page.',
+          description: 'Number of unique frames found across the page(s).',
           count: totalFrames,
           expand: isExpanded,
         },
         {
           title: 'Number of Frames with Associated Cookies',
-          description: 'Frames that have cookies associated with them.',
+          description: 'Unique frames that have cookies associated with them.',
```
Comment (ayushnirwal) [inline packages/design-system/src/components/cookiesLanding/cookiesMatrix/index.tsx:100]:
```suggestion
          description: 'Unique frames across the page(s) that have cookies associated with them.',
```

**Review by ayushnirwal — APPROVED** [review]
