### PR TITLE
Fix: Affected cookies csv output

### LINKED ISSUE #284: Affected cookies report show cookies with “Cookies Affected” = FALSE
**Describe the bug**
Affected cookies report show cookies with “Cookies Affected” = FALSE 

**To Reproduce**
1. Generate report (websites that reproduced the issue on my end: https://www.mercadopago.com.ar, https://www.rakuten.co.jp) using [CLI](https://github.com/GoogleChromeLabs/ps-analysis-tool/wiki/A.-PSAT's-How-To#build-and-run-psats-cli)
2. Open the report
3. Export the report via the export button on the report
4. Import the following affected-cookies.csv and cookies.csv on any spreadsheet
5. Find that affected-cookies.csv only has cookies with the column "Cookie Affected" set to `FALSE`, which indicate the column only shows cookies that are NOT affected

**Expected behavior**
The cookies list in the affected-cookies.csv should show cookies that are affected

**Screenshots**
Screenshot 2023-11-20 at 12 18 23

**Desktop (please complete the following information):**
- OS: Macbook Pro Intel, Sonoma 14.1
- PSAT version : [v0.3.2](https://github.com/GoogleChromeLabs/ps-analysis-tool/releases/tag/v0.3.2)

**Additional context**
- The CLI localhost report shows only 3 cookies under Affected Cookies tab, but not sure which one is the source of truth because of the issue #283.

### PR DESCRIPTION
**Pull request by ayushnirwal**
## Description

It was observed (in issue #284) that in the exported reports in the CSV files the values of the column `Cookie Affected` was flipped. This PR fixes the wrong value serialization and removes the column `Cookie Affected` from the `affected-cookies.csv` file due to it being redundant since all cookies listed in that file are affected. 

## Related technical choices
- Added a utility function in `./packages/common/src/utils/sanitizeCsvRecord.ts` for converting a string into a valid CSV record according to [RFC](https://datatracker.ietf.org/doc/html/rfc4180). 

Fixes #284

### CODE REVIEW

**Comment by ayushnirwal** [comment]
QA issue #312 resolved.

File: packages/cli-dashboard/src/components/utils/reportDownloader.ts [hunk 1]
```diff
@@ -32,6 +33,9 @@ interface NewReport extends CompleteJson {
 
 type SanitisedCookieType = ParsedCookie & {
```
Comment (amovar18) [inline packages/cli-dashboard/src/components/utils/reportDownloader.ts:34]: Can we move `SanitisedCookieType` and `SingleTechnology` to `types.ts`

**Review by amovar18 — APPROVED** [review]
LGTM!
Requested a small change. Rest looks fine.
