### PR TITLE
Fix: Clear cookie preview area

### LINKED ISSUE #351: [QA] Enhancement: Clear "Cookie Preview Area" on filter application for improved data visibility
When filters are applied, they consider multiple parameters. If the selected row doesn't meet the criteria of the applied filter, it can lead to confusion. With the latest filters, none of the rows may be selected, and the cookie preview area may display data from a row that is not currently visible.

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/15173772/92fc0e7b-c93c-4cdd-bcd5-53c68cdccba8

### PR DESCRIPTION
**Pull request by amovar18**
## Description
This PR aims to fix the cookie preview area once the cookie is not present anymore in the table view.

## Testing Instructions
- Clone this branch.
- In the terminal run `npm start`.
- Open a fresh instance of the browser and analyse the page with the PSAT tool in DevTool.
- In the table select a 1P cookie then apply the `scope` filter for 3P cookies, you should see the cookie details area being cleared.

## Screenshot/Screencast

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/59614577/774710f7-1f47-4150-88c8-26a6f6ccfd62

---

## Checklist

- [x] I have thoroughly tested this code to the best of my abilities.
- [x] I have reviewed the code myself before requesting a review.
- [x] This code is covered by unit tests to verify that it works as intended.
- [x] The QA of this PR is done by a member of the QA team (to be checked by QA).

Fixes #351

### CODE REVIEW

File: packages/design-system/src/components/table/useTable/provider.tsx [hunk 1]
```diff
@@ -121,6 +126,25 @@ export const TableProvider = ({
...
+        );
+        return tableCookieKey === selectedKey;
+      });
+
+      if (filteredRows.length === 0) {
+        onRowClick(null);
+      }
+    }
+  }, [selectedKey, onRowClick, rows]);
+
```
Comment (mayan-000) [inline packages/design-system/src/components/table/useTable/provider.tsx:147]: Need to add new optional callback prop for clearing row, can't put specific code inside table.

- A callback can be created in `CookieTable` component, which handles filtering callback.
- Use the callback, if passed as prop, unless always return true.

```suggestion
  useEffect(() => {
      const filteredRows = rows.filter((row) => isRowSelected?.(row.originalData) ?? true);

      if (filteredRows.length === 0) {
        onRowClick(null);
      }
  }, [onRowClick, rows]);

```

Comment (amovar18) [reply packages/design-system/src/components/table/useTable/provider.tsx]: Resolved in latest commit.

File: packages/design-system/src/components/cookieDetails/details.tsx [hunk 2]
```diff
@@ -100,19 +100,17 @@ const Details = ({ selectedCookie, isUsingCDP }: DetailsProps) => {
...
+        <>
+          <p className="font-bold text-raising-black dark:text-bright-gray mb-1">
+            Blocked Reason
+          </p>
+          <p
+            className="text-outer-space-crayola dark:text-bright-gray"
+            dangerouslySetInnerHTML={{ __html: blockedReasons ?? '' }}
+          />
+        </>
+      )}
```
Comment (ayushnirwal) [inline packages/design-system/src/components/cookieDetails/details.tsx:113]: @amovar18 I remember having a discussion about this. Would you mind adding  comments about this in your PR description.

File: packages/design-system/src/components/table/useTable/provider.tsx [hunk 3]
```diff
@@ -121,6 +122,15 @@ export const TableProvider = ({
...
   );
 
+  useEffect(() => {
+    const filteredRows = rows.filter(
+      (row) => isRowSelected?.(row.originalData) ?? true
+    );
+
+    if (filteredRows.length === 0) {
+      onRowClick(null);
+    }
```
Comment (ayushnirwal) [inline packages/design-system/src/components/table/useTable/provider.tsx:132]:
```suggestion
    const isSomeRowSelected = rows.some(
      (row) => isRowSelected?.(row.originalData) ?? true
    );
    
    if (!isSomeRowSelected){
      onRowClick(null);
    }
```

File: packages/extension/src/serviceWorker/index.ts [hunk 4]
```diff
@@ -516,8 +516,9 @@ chrome.debugger.onEvent.addListener((source, method, params) => {
       ? cookie.domain.slice(1)
       : cookie?.domain;
 
-    // Adding alternate domains here because our extension calculates domain differently that the application tab.
-    // This is done to capture both NID.google.com/ and NIDgoogle.com/ so that if we find either of the cookie we add issues to the cookie object
+    if (!domainToUse) {
+      return;
+    }
```
Comment (ayushnirwal) [inline packages/extension/src/serviceWorker/index.ts:521]: I think this check can be an early return. it can be clubbed with the condition on line 504-507 or a additional check after that.

File: packages/extension/src/utils/processAndStoreDocumentCookies.ts [hunk 5]
```diff
@@ -53,6 +53,8 @@ const processAndStoreDocumentCookies = async ({
           parsedCookie.domain = singleCookie.domain?.startsWith('.')
             ? singleCookie.domain
             : '.' + singleCookie.domain;
+        } else {
+          parsedCookie.domain = window.location.hostname;
```
Comment (ayushnirwal) [inline packages/extension/src/utils/processAndStoreDocumentCookies.ts:57]: It is not immediately obvious to me that how does this change help in this PR's aim. Would you mind adding some context in the PR description?

File: packages/design-system/src/components/cookieDetails/details.tsx (hunk 2 above)
Comment (amovar18) [reply packages/design-system/src/components/cookieDetails/details.tsx:113]: This was to make sure the blocking reason being displayed follows the same logic that is used to display the blocking status.

File: packages/extension/src/utils/processAndStoreDocumentCookies.ts (hunk 5 above)
Comment (amovar18) [reply packages/extension/src/utils/processAndStoreDocumentCookies.ts:57]: It was a small bug fix that was noticed while self-testing the PR so added this here.
